# Generated by Django 5.2.16 on 2026-07-10 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['artist__name', 'title']},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='city',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='museum_name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['country', 'city', 'name'],
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='museum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='zettels.museum'),
        ),
    ]
