# Generated by Django 5.2.16 on 2026-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettels', '0003_alter_artist_id_alter_artwork_id_alter_museum_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='region',
            field=models.CharField(blank=True, choices=[('europe', 'Europe'), ('north_america', 'North America'), ('latin_america', 'Latin America'), ('asia', 'Asia'), ('africa', 'Africa'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
