# Generated by Django 5.2.16 on 2026-07-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettels', '0004_museum_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(choices=[('cuba_diaspora', 'Cuba / Diaspora'), ('international', 'International')], max_length=20)),
                ('homepage_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='PressMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='press_mentions', to='zettels.artist')),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='press_mentions', to='zettels.artwork')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='zettels.publication')),
            ],
            options={
                'ordering': ['-published_year', '-published_date'],
            },
        ),
    ]
